### ISSUE TITLE
Discussion: Publishing to npm - semver, commitizen

### ISSUE THREAD

**Issue by johnjacobkenny** [zellwk/zellwk.com#104]
I went through the article https://github.com/zellwk/zellwk.com/blob/master/src/posts/2019-03-20-publish-to-npm.md and it was very informative. I am curious about how we might integrate this with tools like commitizen and semver which may generate the next release version number automatically based on the commits that went in.

**Comment by zellwk** [comment]
The `np` tool I recommended integrates Semver automatically Semver

**Comment by johnjacobkenny** [comment]
Yes but it prompted explicitly for the number, is there a way for it to automatically generate the right number as mentioned here https://github.com/semantic-release/semantic-release

**Comment by zellwk** [comment]
It auto populates a few numbers you can choose from. I think that's good enough. You can skip the choosing by adding keywords like `patch` if you wish to though. 

I don't think there's a way any program can automate patch / minor / major versions without explicit consent from developers.

**Comment by johnjacobkenny** [comment]
Actually the semantic-release link I mentioned above creates the version number automatically based on the commit message format (enforced by commitizen). But yes, thanks for the inputs :smiley:
