### ISSUE TITLE
Combobox with aria-activedescendant (Method 2) - works with Voiceover when input IS NOT empty

### ISSUE THREAD

**Issue by Numel2020** [zellwk/zellwk.com#106]
Was experimenting with your codesandbox
[Combobox with aria-activedescendant (Method 2)](https://codepen.io/zellwk/pen/zYxJQEj)
The voice over seems to work now when the input has text in it. I tested this on chrome for mac ios

**Comment by zellwk** [comment]
Test this on Safari.
