### ISSUE TITLE
Git Bash Windows Terminal with WSL as default directory

### ISSUE THREAD

**Issue by foxfabi** [zellwk/zellwk.com#115]
I was able to set up the Git Bash as the default shell wich opens a terminal with the WSL as default directory.

1. [Add Git-Bash to the new Windows Terminal](https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal): Based on this article i added the git bash as windows terminal profile.
2. To set the starting directory of the terminal, set `startingDirectory` to desired folder. See [Profile settings in Windows Terminal](https://aka.ms/terminal-profile-settings)

```json
    "profiles":
    {
        "defaults":
        {
            "startingDirectory": "//wsl$/Debian/",
        },
        "list":
        [
            {
              "guid": "{00000000-0000-0000-ba54-000000000002}",
              "hidden": false,
              "name": "Git Bash",
              "commandline": "%PROGRAMFILES%/git/usr/bin/bash.exe -i -l",
              "icon": "%PROGRAMFILES%/Git/mingw64/share/git/git-for-windows.ico",
            }
        ]
    },

**Comment by zellwk** [comment]
@foxfabi It's great you managed to setup Git bash as the default shell. I don't intend to do that though, so I'd be closing this issue. Thanks for sharing!
