### ISSUE TITLE
Question: When using relative units, how do you prevent non whole pixel values?

### ISSUE THREAD

**Issue by toddpadwick** [zellwk/zellwk.com#138]
First of all your article is really helpful - so thank you for publishing it! Vertical rhythm is something I've always tried to apply but never quite known the best way to do so. But Im still a little unsure on relative units. Until now, I've simply set the following as an scss variable:
`$xs-baseline:24px`
`$lg-baseline:28px`

and then applied all height-related measurements as a multiple of these throughout my entire site. for example:

```
h1 {
    font-size:60px;
    line-height:$xs-baseline * 3;
    margin-bottom:$xs-baseline * 2;
    @include breakpoint(lg) {
        font-size:76px;
        line-height:$lg-baseline * 3;
        margin-bottom:$lg-baseline * 2;
    }
}

.logo {
    height:$xs-baseline * 2;
    margin-bottom:$xs-baseline;
    @include breakpoint(lg) {
         height:$lg-baseline * 2;
        margin-bottom:$lg-baseline;
    }
}

```

I have always been aware I should switch to relative units, but I've never quite understood how - as whenever I've tried, I end up with non-whole pixel values which is not so bad with fonts, but when you have things like SVG icons or graphics, their heights not being explicitly defined as pixels means you risk them being fuzzy and not crisp. The way I've been doing it above is tedious, especially when I need to switch the baseline value for mobile and desktop, but it does mean I know that I can ensure all my graphics are a multiple of `24px` or `28px` as I can be completely confident that everything is always going to be a multiple of them.

So I wondered if you could help me understand your use of relative units a little more and how to handle this better? Any advice would be really appreciated :)

**Comment by zellwk** [comment]
You don't prevent it. Let it be, it'll be +1px or -1px. The difference won't be obvious especially when there's enough repetition.
