### ISSUE TITLE
Inconsistent button clicking behavior: "potential fix" modification

### ISSUE THREAD

**Issue by pcafstockf** [zellwk/zellwk.com#141]
Thank you for your article on [Inconsistent behavior among browsers when clicking on buttons](https://zellwk.com/blog/inconsistent-button-behavior/).  It was both surprising and enlightening.

I also appreciate your suggested fix for the problem and tend to agree that the Chrome implementation makes the most sense.

Testing shows that Chrome fires the `blur` **before** the `click`, so I modified the "fix" to be a little more general and to invoke `focus` on the way down (the capturing phase), instead of on the way back up (bubbling phase).

```
window.document.addEventListener('click', function (event) {
	if (event.target && event.target !== window.document.activeElement && typeof (<any>event.target).focus === 'function')
		(<any>event.target).focus();
}, {capture: true});
```

This seems to be working, but I have only tested it on Safari and Mac Chrome.   
Do you have any suggestions or criticism of this modification?

**Comment by zellwk** [comment]
There's no real practical difference imo.
