### ISSUE TITLE
Issue with deploying to an AWS EC2 Machine

### ISSUE THREAD

**Issue by ixopp** [zellwk/zellwk.com#145]
Hi there,
I'm having an issue where I can't seem to get rsync with the EC2 server working. I have tried the methods that was in your website, however it seems to get stuck in the known hosts saying it can't find the file or something. Alternatively it also gives an error with rsync taking too long and the connection timing out. Current in order for me to ssh into the server I need to use a pem file to log in

Any advice?

**Comment by zellwk** [comment]
Unfortunately no. I'm not skilled enough to debug this without exploring further.
