### ISSUE TITLE
a missing quotation mark throwing a piece of code out of a block

### ISSUE THREAD

**Issue by mechee55** [zellwk/zellwk.com#19]
![Screen Shot 2019-04-24 at 12 12 11 AM](https://user-images.githubusercontent.com/27831876/56639817-63c29e00-6626-11e9-903d-37b77ab509fe.png)

the `img` tag inside the `figure` is missing a closing `"`
this throws the code below out of a code block.

```
const getOne =_=> {
   return sleep(1000).then(v=1)
}
```

**Comment by zellwk** [comment]
Good catch. Fixing it.
