### ISSUE TITLE
2018-12-12-check-empty-input-css.md

### ISSUE THREAD

**Issue by surgeboris** [zellwk/zellwk.com#2]
```
pattern="\s*\S+.*"
```
seems to `match`/`not match` your input strings properly:
```
// Should not match
''
' '
'  '
'   '

// Should match
'one-word'
'one-word '
' one-word'
' one-word '
'one phrase with whitespace'
'one phrase with whitespace '
' one phrase with whitespace'
' one phrase with whitespace '
```
it was very easy for me to come up with it, so I wonder: am I missing something? What was your difficulty with creating proper RegExp?

**Comment by zellwk** [comment]
Patterns updated on the blog post.
