### ISSUE TITLE
What if SSH_USER change after the connection?

### ISSUE THREAD

**Issue by RomanShyba** [zellwk/zellwk.com#219]
![ssh](https://user-images.githubusercontent.com/38078727/227506017-a95924c6-16da-4cfb-b362-131fc22f602f.png)

So if I set full path ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/the/folder, it didn't connect. First I need to connect to ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} and then go to /path/to/the/folder. After it, I replace files. Do you have any ideas on how to implement that without "git pull"?

**Comment by zellwk** [comment]
Hey @RomanShyba, I don't give advice or solve problems here in these Github issues. 

Best place to ask would be inside my community.

**Comment by RomanShyba** [comment]
@zellwk Thanks for your response. I thought that you may already have faced this problem. Where can I find your community?

**Comment by zellwk** [comment]
Here you go: https://magicaldevschool.com/dojo/
