### ISSUE TITLE
Broken Images showing as markdown

### ISSUE THREAD

**Issue by justsml** [zellwk/zellwk.com#40]
It looks like your fantastic article on [asking questions](https://zellwk.com/blog/asking-questions/) has some missing image(s):

![image](https://user-images.githubusercontent.com/397632/62742240-00a11f80-b9fb-11e9-95bd-ca57567289a7.png)

**Comment by zellwk** [comment]
Thanks, just fixed this.

**Comment by justsml** [comment]
Thanks Zell! 😻
