### ISSUE TITLE
[setup] npm run dev and npm run server both fail 

### ISSUE THREAD

**Issue by nisarhassan12** [zellwk/zellwk.com#69]
Error: ENOENT: no such file or directory, open './secrets/variables.env'
![image](https://user-images.githubusercontent.com/46004116/77133991-f9f58300-6a86-11ea-92cb-9cce199d4bb0.png)

**Comment by zellwk** [comment]
[Here's how I protect and sync my secret keys](https://zellwk.com/blog/environment-variables/). You will have to create this `variables.dev` if you want to use for your projects. I'm not sharing them publicly.

**Comment by nisarhassan12** [comment]
Thanks!  @zellwk I work for https://gitpod.io (a free online VS Code like IDE) and we are currently on a mission to simplify contributors onboarding by fully automating the dev environments for popular OSS projects. You can find a list of them at https://contribute.dev

![image](https://user-images.githubusercontent.com/46004116/77154724-0f39d400-6abe-11ea-86c6-2492be149d1f.png)

I was looking to simplify contributors onboarding for this repo. Do you accept code contributions :) for the site ?

**Comment by zellwk** [comment]
Sounds cool.
