### ISSUE TITLE
unable to replicate the first async example

### ISSUE THREAD

**Issue by aspiringguru** [zellwk/zellwk.com#75]
I was unable to replicate the async example. is this what you were using?

I think "const control = async _ => " does not get started, hence no result.

const sleep = ms => {
  return new Promise(resolve => setTimeout(resolve, ms))
}

const getNumFruit = fruit => {
  return sleep(1000).then(v => fruitBasket[fruit])
}

const control = async _ => {
  console.log('Start')

  const numApples = await getNumFruit('apple')
  console.log(numApples)

  const numGrapes = await getNumFruit('grape')
  console.log(numGrapes)

  const numPears = await getNumFruit('pear')
  console.log(numPears)

  console.log('End')
}

--------------------------------------------------------------
https://aspiringguru.github.io/async_await_loop_fetch_tut/demo_x_broken.html
https://github.com/aspiringguru/async_await_loop_fetch_tut/blob/master/demo_x_broken.html

**Comment by zellwk** [comment]
Did you run the function?

**Comment by aspiringguru** [comment]
found my mistake.

added starting of the async function at end of the script and renamed the file.

https://aspiringguru.github.io/async_await_loop_fetch_tut/demo_async_promise_random_sleep.html
[view with developers console open]

thanks for the reminder of the obvious :)

closed.
