### ISSUE TITLE
Mentionning Jest Mongo package in setup

### ISSUE THREAD

**Issue by willthefirst** [zellwk/zellwk.com#80]
Hey there, thanks for writing up this article. It's been helpful.

I struggled to get things to work for a while, and found that I had to install the package that Jest recommends here: https://jestjs.io/docs/en/mongodb

Might be worth mentioning.

**Comment by zellwk** [comment]
Interesting! that wasn't available in the Jest docs when I tried it before. Will definitely give it a test run when I Find some time to work through it. 

Can you share with me what you struggled to get things to work, and how this package helped you? That'll be super helpful. 

Thanks!

**Comment by willthefirst** [comment]
Totes.

In case you hadn't seen it, Mongoose officially recommends [against using Jest.](https://mongoosejs.com/docs/jest.html)

Per the recs in the official Jest Mongo docs, I **removed** `jest.config.js` which contained `testEnvironment: node`. I am not sure if that's necessary, but it's what the Jest Mongo docs recommended. Then, I threw the following code into a file called `jest.mongodb.config.js`, 

```node
module.exports = {
  mongodbMemoryServerOptions: {
    instance: {
      dbName: 'jest'
    },
    binary: {
      version: '4.0.3',
      skipMD5: true
    },
    autoStart: false
  }
};
``` 
Beyond that, I'd only recommend adding `useUnifiedTopology: true,` to the `mongoose.connect` config object (this is something Mongoose now asks you to  do).

**Comment by zellwk** [comment]
Interesting. Thanks for sharing. I'll try it when I have a chance to!

**Comment by zellwk** [comment]
Just worked on this recently. I ended up going with `mongodb-memory-server` instead.
