### ISSUE TITLE
Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by awesomesolution** [zellwk/zellwk.com#90]
At very first when i download and run the code it gives me this error:

`
fs.js:120
    throw err;
    ^

Error: ENOENT: no such file or directory, open './secrets/variables.env'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
`

My suggestion is we should keep "dev.env" and "production.env" file as a separate and could include it it based on the environment.

Thanks

**Comment by zellwk** [comment]
If you have the time you can send in a PR for this.
